### DISCUSSION TITLE
Metadaten Icon bei Layern im TOC

### DISCUSSION THREAD

**Discussion by faulgurke** [e-netze/webgis-community#15] [Q&A]
Folgende Definition gilt derzeit in der **ui.css** für das Icon icon-info:

```css
.webgis-api-icon-info {
	background-image: url(img/ui/help-16.png);
}
```

Sollte das Bild nicht **info-16.png** heißen zumal das icon-help wie folgt definiert ist?

```css
.webgis-api-icon-help {
	background-image: url(img/ui/help-16.png);
}
```
